### ISSUE TITLE
Speaker in BOM

### ISSUE THREAD

**Issue by larsbrinkhoff** [aspro648/OSTR#1]
Hello,

I don't see the speaker in the V2 BOM.

**Comment by aspro648** [comment]
Sorry Lars, that is my mistake.  It didn't make it into the kit either.
I'll get one in the mail to you.

It is - 1 ea. Piezo speaker, [TDK PS1240P02CT3](
https://www.digikey.com/short/zndnmn)


*Ken Olsen*
648.ken@gmail.com | www.MakersBox.us <http://www.makersbox.us/>
<http://www.facebook.com/648.ken>  <http://linkedin.com/in/olsenken>

**Comment by larsbrinkhoff** [comment]
Thanks!

**Comment by larsbrinkhoff** [comment]
Updated BOM seems fine.

PS. Being a fan of the PDP families of computers, it was a thrill seeing our name!
